// Generated by CoffeeScript 1.10.0
(function() {
  var DingTalkReturnError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DingTalkReturnError = (function(superClass) {
    extend(DingTalkReturnError, superClass);

    function DingTalkReturnError(err_code, err_msg) {
      this.name = 'DingTalkReturnError';
      this.message = err_msg;
      this.code = err_code;
    }

    DingTalkReturnError.prototype.toString = function() {
      return this.name + ": [" + this.code + "] " + this.message;
    };

    return DingTalkReturnError;

  })(Error);

  module.exports = {
    DingTalkReturnError: DingTalkReturnError
  };

}).call(this);

//# sourceMappingURL=errors.js.map
