// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, config, err_filter, errors, rp;

  rp = require('request-promise');

  Promise = require('bluebird');

  errors = require('../errors');

  _ = require('lodash');

  config = require('./interfaceConfig');

  err_filter = function(data) {
    if (data.errcode !== 0) {
      return Promise.reject(new errors.DingTalkReturnError(data.errcode, data.errmsg));
    }
    delete data.errcode;
    delete data.errmsg;
    return Promise.resolve(data);
  };

  module.exports = function(uri, params, model) {
    var c, method, options;
    if (!_.has(config, uri)) {
      return Promise.reject(new Error('暂未提供该接口的配置'));
    }
    c = config[uri];
    method = c.method || 'GET';
    uri = "https://oapi.dingtalk.com" + uri;
    options = {
      method: method,
      uri: uri,
      json: true
    };
    return ((function() {
      if (c.token) {
        return model.getToken();
      } else if (c.sns_token) {
        return model.getSnsToken();
      } else {
        return Promise.resolve(null);
      }
    })()).then(function(token) {
      if (method === 'GET') {
        if (token != null) {
          params.access_token = token;
        }
        options.qs = params;
      } else {
        if (token != null) {
          options.qs = {
            access_token: token
          };
        }
        options.body = params;
      }
      return rp(options).then(err_filter);
    });
  };

}).call(this);

//# sourceMappingURL=index.js.map
